{% set version = "0.12.0" %}

package:
  name: quantities
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/quantities/quantities-{{ version }}.tar.gz
  sha256: 19817b69b5aaf45b96800e21f089f76850667f7a83692bdd911124cff7545290

build:
  number: 0
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - quantities
    - quantities.constants
    - quantities.units

about:
  home: http://python-quantities.readthedocs.org/en/latest/
  license: BSD 3-Clauses
  summary: 'Physical quantities with units, based upon numpy.'

extra:
  recipe-maintainers:
      - ocefpaf
