# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Jbz1BXa8wyJl7EAWjwh0QRQIvrMiw3y8Ki0Z/WX90qejpHQ01v17pRKUiIXcq+sdistB7Vnl03EY3ShFlWAY2/ky1AodBGI3so9d3vxVG1v/JaBSn+LOLlvrmdMz2/UVZLDanZTttKQmd7nlSTMMK0LCRGP8mFrvzJWuuqbm0uFvBn77kWIw3NlEiG2IM6PLxf/UhpFC98+KeSAAT+b6eIRJEtlkY8aFU1elZ54VUZa1uhFsfQA685QAfyalj8d5HrN91EjKeYqHu0+LVH/wOgqgzrHwZBu+Ko6s8ww+JcJobSP9vhsPj3zi1qlaG8gNHXYNOc2VgOfhPjYz/uGu2Mu17zkieOBSKps1y/6K8dzbWr6XT/9jL1l13cVH2f5cqpkXY/mu7bCPscfVzkE4yCuAxIMTsTMT+Waq2J2tM6UtEOrXwzXsThCZKleVTOrDrXMBWGG7yiaiHWSrLmw83oEcebnD/nyOzJr0nXAICtHQ+RjS/9UeXn31/VBsO9hMr/4tGx1YkXW6RQfQSZm4o/kDujpXpWs3mQ0+5j3jArn1r6cqX3Ts93ya8CuXnhEUrpVvVXqDiz1Ub6GckNMpjf6sREb787Ytrkl5LatuU4CIByPXKJSFAm+mozl+upmxdbSPa5F8s7HpyUscGf0BUYorDwNCQ76/d2NDf6nn6Wk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
