travis:
  secure:
    BINSTAR_TOKEN: Jbz1BXa8wyJl7EAWjwh0QRQIvrMiw3y8Ki0Z/WX90qejpHQ01v17pRKUiIXcq+sdistB7Vnl03EY3ShFlWAY2/ky1AodBGI3so9d3vxVG1v/JaBSn+LOLlvrmdMz2/UVZLDanZTttKQmd7nlSTMMK0LCRGP8mFrvzJWuuqbm0uFvBn77kWIw3NlEiG2IM6PLxf/UhpFC98+KeSAAT+b6eIRJEtlkY8aFU1elZ54VUZa1uhFsfQA685QAfyalj8d5HrN91EjKeYqHu0+LVH/wOgqgzrHwZBu+Ko6s8ww+JcJobSP9vhsPj3zi1qlaG8gNHXYNOc2VgOfhPjYz/uGu2Mu17zkieOBSKps1y/6K8dzbWr6XT/9jL1l13cVH2f5cqpkXY/mu7bCPscfVzkE4yCuAxIMTsTMT+Waq2J2tM6UtEOrXwzXsThCZKleVTOrDrXMBWGG7yiaiHWSrLmw83oEcebnD/nyOzJr0nXAICtHQ+RjS/9UeXn31/VBsO9hMr/4tGx1YkXW6RQfQSZm4o/kDujpXpWs3mQ0+5j3jArn1r6cqX3Ts93ya8CuXnhEUrpVvVXqDiz1Ub6GckNMpjf6sREb787Ytrkl5LatuU4CIByPXKJSFAm+mozl+upmxdbSPa5F8s7HpyUscGf0BUYorDwNCQ76/d2NDf6nn6Wk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
